version: '3'
services:
  chentool-app: # 前端node容器(运行nginx中的Vue项目)
    image: chentool-app_image
    container_name: chentool-app_container
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ../                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: docker/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"                      # 映射端口
      - "443:443"                      # 映射端口
    volumes:
      - /usr/local/cert/index:/etc/nginx/cert     # 证书映射
#      - /etc/localtime:/etc/localtime:ro     # 主机本机时间文件映射 与本机时间同步
    networks:
      - chentool-app-network          # 设置网卡

networks:
  chentool-app-network:
    driver: bridge
