version: '3.9'
name: chentool-app
services:
  chentool-app: # 前端node容器(运行nginx中的Vue项目)
    image: chentool-app
    container_name: chentool-app
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ../                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: docker/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8083:8083"
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"
      - "/var/log/project/chentool-app:/var/log/nginx"
#      - "/usr/local/cert/index:/etc/nginx/cert"
    networks:
      - chentool_chentool-network

networks:
  chentool_chentool-network:
    external: true